# Generated by Django 5.0.1 on 2024-03-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_creation.message'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='New Conversation', max_length=20),
        ),
    ]
