# Generated by Django 5.0 on 2024-01-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityScoreBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CharacterProficiencies',
        ),
        migrations.DeleteModel(
            name='CharacterProficiencyCustomValues',
        ),
        migrations.AlterModelOptions(
            name='armourproficiency',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='proficiency',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='toolproficiency',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='weaponproficiency',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RenameField(
            model_name='savingthrow',
            old_name='statistic',
            new_name='ability',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='statistic',
            new_name='ability',
        ),
        migrations.AddField(
            model_name='proficiency',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='race',
            name='alignment_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='race',
            name='language_desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(to='character_creation.language'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='languages',
            field=models.ManyToManyField(blank=True, to='character_creation.language'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='starting_proficiencies',
            field=models.ManyToManyField(blank=True, to='character_creation.proficiency'),
        ),
        migrations.AddField(
            model_name='trait',
            name='subraces',
            field=models.ManyToManyField(to='character_creation.subrace'),
        ),
        migrations.AlterField(
            model_name='race',
            name='size_desc',
            field=models.TextField(default=''),
        ),
        migrations.RenameModel(
            old_name='Statistic',
            new_name='Ability',
        ),
        migrations.AddField(
            model_name='abilityscorebonus',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character_creation.ability'),
        ),
    ]
