# Generated by Django 5.0 on 2024-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0002_abilityscorebonus_delete_characterproficiencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='desc',
        ),
        migrations.AddField(
            model_name='language',
            name='script',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='ERR_NO_NAME'),
        ),
        migrations.AlterField(
            model_name='language',
            name='typical_speakers',
            field=models.CharField(default=''),
        ),
    ]
