# Generated by Django 5.0.1 on 2024-03-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0002_alter_conversation_messages_alter_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='thread_id',
            field=models.CharField(blank=True),
        ),
    ]
