# Generated by Django 5.0 on 2024-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0003_remove_language_desc_language_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(default='ERR_NO_NAME', unique=True),
        ),
    ]
