# Generated by Django 5.0.1 on 2024-03-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0003_conversation_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
