# Generated by Django 5.0 on 2024-01-25 17:32

import character_creation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0004_alter_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='desc_long',
        ),
        migrations.RemoveField(
            model_name='race',
            name='desc_short',
        ),
        migrations.AddField(
            model_name='race',
            name='ability_score_bonuses',
            field=models.ManyToManyField(to='character_creation.abilityscorebonus'),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed_burrowing',
            field=models.PositiveSmallIntegerField(default=0, validators=[character_creation.models.validate_mod_five]),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed_climbing',
            field=models.PositiveSmallIntegerField(default=0, validators=[character_creation.models.validate_mod_five]),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed_flying',
            field=models.PositiveSmallIntegerField(default=0, validators=[character_creation.models.validate_mod_five]),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed_swimming',
            field=models.PositiveSmallIntegerField(default=0, validators=[character_creation.models.validate_mod_five]),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed_walking',
            field=models.PositiveSmallIntegerField(default=30, validators=[character_creation.models.validate_mod_five]),
        ),
    ]
