# Generated by Django 5.0 on 2024-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0005_remove_race_desc_long_remove_race_desc_short_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrace',
            name='starting_proficiencies',
        ),
        migrations.AddField(
            model_name='subrace',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
    ]
