# Generated by Django 5.0.1 on 2024-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0006_alter_conversation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='active',
        ),
    ]
