# Generated by Django 5.0 on 2024-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0007_remove_trait_races_remove_trait_subraces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrace',
            name='ability_score_bonuses',
            field=models.ManyToManyField(to='character_creation.abilityscorebonus'),
        ),
    ]
