# Generated by Django 5.0 on 2024-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0008_subrace_ability_score_bonuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='raw_stats',
        ),
        migrations.DeleteModel(
            name='RawStats',
        ),
    ]
