# Generated by Django 5.0 on 2024-01-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0009_remove_character_raw_stats_delete_rawstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
