# Generated by Django 5.0 on 2024-01-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0010_skill_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='equipment_category',
        ),
        migrations.AlterField(
            model_name='race',
            name='starting_proficiencies',
            field=models.ManyToManyField(blank=True, to='character_creation.proficiency'),
        ),
        migrations.AlterField(
            model_name='race',
            name='traits',
            field=models.ManyToManyField(blank=True, to='character_creation.trait'),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='traits',
            field=models.ManyToManyField(blank=True, to='character_creation.trait'),
        ),
        migrations.DeleteModel(
            name='MagicItem',
        ),
        migrations.AddField(
            model_name='item',
            name='equipment_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='character_creation.equipmentcategory'),
        ),
    ]
