# Generated by Django 5.0.1 on 2024-03-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0010_alter_character_cha_mod_alter_character_cha_save_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='cantrips',
        ),
    ]
