# Generated by Django 5.0 on 2024-01-29 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0011_remove_item_equipment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='value_copper',
        ),
        migrations.RemoveField(
            model_name='item',
            name='value_gold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='value_silver',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.AddField(
            model_name='armour',
            name='weight',
            field=models.CharField(default='', help_text='weight of the armour, measured in pounds (lbs).', max_length=5),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_unit',
            field=models.CharField(choices=[('CP', 'Copper'), ('SP', 'Silver'), ('GP', 'Gold')], default='CP'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_value',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='armour',
            name='strength_requirement',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
