# Generated by Django 5.0.1 on 2024-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0012_character_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M  ', max_length=1),
        ),
    ]
