# Generated by Django 5.0 on 2024-01-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0012_remove_item_value_copper_remove_item_value_gold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armour',
            old_name='armor_type',
            new_name='armour_type',
        ),
    ]
