# Generated by Django 5.0 on 2024-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0013_rename_armor_type_armour_armour_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armour',
            name='description',
        ),
        migrations.AlterField(
            model_name='armour',
            name='ac_dex_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='armour',
            name='stealth_disadvantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='savingthrowproficiency',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='skillproficiency',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='starting_proficiencies',
            field=models.ManyToManyField(blank=True, to='character_creation.proficiency'),
        ),
    ]
