# Generated by Django 5.0.1 on 2024-03-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0013_character_proficiency_bonus_alter_character_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hit_dice_remaining_and_total',
            field=models.CharField(default='1/1'),
        ),
    ]
