# Generated by Django 5.0.1 on 2024-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0015_remove_character_acrobatics_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cha_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='con_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='int_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='str_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_save',
            field=models.BooleanField(default=False),
        ),
    ]
