# Generated by Django 5.0 on 2024-02-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0015_alter_weapon_effective_range_alter_weapon_max_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('FI', 'fire'), ('BL', 'bludgeoning'), ('RA', 'radiant'), ('NE', 'necrotic'), ('PS', 'psychic'), ('CO', 'cold'), ('FO', 'force'), ('EL', 'elemental'), ('LI', 'lightning'), ('PI', 'piercing'), ('TH', 'thunder'), ('AC', 'acid'), ('PO', 'poison'), ('SL', 'slashing'), ('PH', 'physical')], default='', null=True),
        ),
    ]
