# Generated by Django 5.0.1 on 2024-03-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0016_character_cha_save_character_con_save_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='profs_and_langs',
            new_name='languages',
        ),
        migrations.AddField(
            model_name='character',
            name='tools',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons_and_armour',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
