# Generated by Django 5.0.1 on 2024-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0017_rename_profs_and_langs_character_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='boons',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='conditions',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
