# Generated by Django 5.0.1 on 2024-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0019_character_allies_and_organisations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_level',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.CharField(default=''),
        ),
    ]
