# Generated by Django 5.0.1 on 2024-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0020_remove_character_character_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterspell',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(blank=True, default='', unique=True),
        ),
    ]
