# Generated by Django 5.0.1 on 2024-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0022_alter_spell_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterspell',
            name='spell',
            field=models.CharField(default=''),
        ),
    ]
