# Generated by Django 5.0.1 on 2024-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0023_alter_characterspell_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterspell',
            name='level',
            field=models.SmallIntegerField(default=0),
        ),
    ]
