# Generated by Django 5.0.1 on 2024-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0024_characterspell_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ep',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='pp',
            field=models.SmallIntegerField(default=0),
        ),
    ]
