# Generated by Django 5.0.1 on 2024-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_creation', '0025_character_ep_character_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.CharField(choices=[('T', 'Tiny'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan')], default='M', max_length=1),
        ),
    ]
