# Generated by Django 5.0.1 on 2024-03-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('character_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ha_user',
            name='characters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_creation.character'),
        ),
        migrations.AlterField(
            model_name='ha_user',
            name='conversations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_creation.conversation'),
        ),
        migrations.AlterField(
            model_name='ha_user',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character_creation.message'),
        ),
    ]
