# Generated by Django 5.0.1 on 2024-03-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ha_user_characters_alter_ha_user_conversations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ha_user',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='ha_user',
            name='conversations',
        ),
        migrations.RemoveField(
            model_name='ha_user',
            name='messages',
        ),
    ]
